apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: microsweeper-quarkus
    app.kubernetes.io/part-of: app-microsweeper-quarkus
  name: microsweeper-quarkus
  namespace: prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: microsweeper-quarkus
    app.kubernetes.io/part-of: app-microsweeper-quarkus
status:
  loadBalancer: {}
